CHUNK_SIZE = 200
CHUNK_OVERLAP = 50
K = 4
INDEX_NAME_CACHE_MEMORY = "crag-semantic-answer-cache"
INDEX_NAME = "self-corrective-rag-langgraph"
IMAGE_DIR = "src/data/images"
DOCUMENTS = ["src/data/AI_Engineer-page1.pdf", "src/data/Tanvir_Ahmed_Enterprise_Demo_RAG_Knowledge_Base.pdf", "src/data/Tanvir_Ahmed_RAG_Knowledge_Base.pdf"]
CACHE_THRESHOLD = 0.90
CACHE_VERSION = "self-rag-v1"
SIMILARITY_THRESHOLD_FIASS = 0.30
SIMILARITY_THRESHOLD_PINECONE = 0.70
